<?php
return array (
  1 => 
  array (
    'catid' => '1',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '1,9,8',
    'catname' => '品牌介绍',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'about',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=1',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_about","list_template":"","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '1',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'pinpaijieshao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  2 => 
  array (
    'catid' => '2',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '2',
    'catname' => '新闻动态',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'news',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=2',
    'items' => '5',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_news","show_template":"show_news","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '2',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xinwendongtai',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  3 => 
  array (
    'catid' => '3',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3',
    'catname' => '产品展示',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'product',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=3',
    'items' => '19',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_product","show_template":"show_product","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '3',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'chanpinzhanshi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  4 => 
  array (
    'catid' => '4',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '4',
    'catname' => '服务专区',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'service',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=4',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_service","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '4',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'fuwuzhuanqu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  5 => 
  array (
    'catid' => '5',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '5',
    'catname' => '在线留言',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'message',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=5',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_message","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '5',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zaixianliuyan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  6 => 
  array (
    'catid' => '6',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '6',
    'catname' => '联系我们',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'contact',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=6',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_contact","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '6',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'lianxiwomen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '品牌介绍',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'about/',
    'catdir' => 'pinpaiinfo',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_aboutid9","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '8',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'pinpaijieshao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  8 => 
  array (
    'catid' => '8',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '1',
    'arrparentid' => '0,1',
    'child' => '0',
    'arrchildid' => '8',
    'catname' => '店铺介绍',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'about/',
    'catdir' => 'info',
    'url' => 'http://localhost/huanteng/index.php?m=content&c=index&a=lists&catid=8',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_aboutid8","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'dianpujieshao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>