<?php
return array (
  26 => 
  array (
    'id' => '26',
    'catid' => '25',
    'typeid' => '0',
    'title' => '“广东省建筑工业化工程技术研究中心”获认定',
    'style' => '',
    'thumb' => 'http://localhost/zhengzhan/uploadfile/2017/0208/20170208105928978.jpg',
    'keywords' => '广东省 研究中心 工程技术',
    'description' => '广东省建筑工业化工程技术研究中心获认定近日，由广东省科技厅获悉，广州机施建设集团有限公司申报的广东省建筑工业化工程技术研究中心顺利   ',
    'posids' => '0',
    'url' => 'http://localhost/zhengzhan/index.php?m=content&c=index&a=show&catid=25&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1486522745',
    'updatetime' => '1486522928',
    'hitsid' => 'c-1-26',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  27 => 
  array (
    'id' => '27',
    'catid' => '25',
    'typeid' => '0',
    'title' => '广州今年投资1225亿建258重点项目计划 将修13条地铁',
    'style' => '',
    'thumb' => '',
    'keywords' => '重点项目 广州 地铁',
    'description' => '撸起袖子加油干!广州重点项目建设今年将继续加大力度推进。记者从广州市发改委获悉，今年广州安排258个重点项目，年度计划投资1225亿元。20   ',
    'posids' => '0',
    'url' => 'http://localhost/zhengzhan/index.php?m=content&c=index&a=show&catid=25&id=27',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1486522854',
    'updatetime' => '1486522877',
    'hitsid' => 'c-1-27',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>